'use strict';

// tests for graphql
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('graphql', '/handler.js', 'graphql');
const orderListQueryEvent = require('./orderListQuery');
const createOrderMutationEvent = require('./createOrderMutation');

describe('graphql', () => {
  before((done) => {
    done();
  });

  it('list orders query should return successfully', () => {
    return wrapped.run(orderListQueryEvent).then((response) => {
      console.log(response)
      expect(JSON.parse(response.body)).to.not.property('errors')
      expect(response.statusCode).to.equal(200);
    });
  });

  it('create order mutation should return successfully', () => {
    return wrapped.run(createOrderMutationEvent).then((response) => {
      console.log(response)
      expect(JSON.parse(response.body)).to.not.property('errors')
      expect(response.statusCode).to.equal(200);
    });
  })
});
